version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Pacific/Auckland"
    groups:
      all:
        patterns:
          - "*"
